services:
  traefik:
    image: traefik:v3.6
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - "8888:8888"
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - ./traefik/acme.json:/acme.json:rw
      - ./traefik/config.yml:/config.yml:ro
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.routers.traefik.entrypoints=http
        - traefik.http.routers.traefik.rule=Host(`traefik.sivacor.org`)
        - traefik.http.middlewares.traefik-auth.basicauth.users=admin:$$2y$$05$$yPv8h3.V9P2MQqN08JHhcuTvcJmmyz4O84oRuBqoHerczO2tQJ8sG
        - traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https
        - traefik.http.routers.traefik.middlewares=traefik-https-redirect
        - traefik.http.routers.traefik-secure.entrypoints=https
        - traefik.http.routers.traefik-secure.rule=Host(`traefik.sivacor.org`)
        - traefik.http.routers.traefik-secure.middlewares=traefik-auth
        - traefik.http.routers.traefik-secure.tls=true
        - traefik.http.routers.traefik-secure.tls.certresolver=cloudflare
        - traefik.http.routers.traefik-secure.tls.domains[0].main=sivacor.org
        - traefik.http.routers.traefik-secure.tls.domains[0].sans=*.sivacor.org
        - traefik.http.routers.traefik-secure.service=api@internal
        - traefik.http.services.traefik.loadbalancer.server.port=888
      placement:
        constraints:
          - "node.role == manager"
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    command:
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.filepath=/dev/stdout"
      - "--configFile=/config.yml"

  mongo:
    image: mongo:4.4
    networks:
      - mongo
    volumes:
      - mongo-data:/data/db
      - mongo-cfg:/data/configdb
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"

  submit:
    networks:
      - proxy
    image: xarthisius/aea-sivacor:latest
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=wt_proxy"
        - "traefik.http.routers.submit.rule=Host(`submit.${domain}`)"
        - "traefik.http.routers.submit.entrypoints=https"
        - "traefik.http.routers.submit.tls=true"
        - "traefik.http.routers.submit.service=submit"
        - "traefik.http.services.submit.loadbalancer.server.port=3000"
        - "traefik.http.services.submit.loadbalancer.passhostheader=true"
    extra_hosts:
      - "girder.${domain}:host-gateway" # for the local queue

  local_worker:
    image: docker.io/xarthisius/girder-sivacor:latest
    networks:
      - celery
      - mongo
    volumes:
      - ./volumes:/srv/data
      - /home/ubuntu/.gnupg:/home/girder/.gnupg
      - /tmp:/tmp
    environment:
      - DOMAIN=${domain}
      - GIRDER_MONGO_URI=mongodb://mongo:27017/girder
      - GIRDER_HOST=0.0.0.0
      - GIRDER_WORKER_BROKER=redis://redis/
      - GIRDER_WORKER_BACKEND=redis://redis/
      - GIRDER_NOTIFICATION_REDIS_URL=redis://redis:6379/
      - GIRDER_LOCAL_FONTELLO_ARCHIVE=/girder/clients/web/static/built/fontello.zip
      - GOSU_USER=1000:1000:${docker_group}
      - HOSTDIR=/
      - GIRDER_SIVACOR_TRO_GPG_PASSPHRASE=${GIRDER_SIVACOR_TRO_GPG_PASSPHRASE}
      - GIRDER_SIVACOR_TRO_GPG_FINGERPRINT=${GIRDER_SIVACOR_TRO_GPG_FINGERPRINT}
    extra_hosts:
      - "girder.${domain}:host-gateway" # for the local queue
    entrypoint: ["/usr/bin/tini", "--", "celery", "--app=girder_worker.app", "worker", "--queues=local", "-c", "2", "--loglevel=INFO"]
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"

  girder:
    image: docker.io/xarthisius/girder-sivacor:latest
    networks:
      - proxy
      - celery
      - mongo
    volumes:
      - ./volumes/base:/srv/data/base
      - /tmp:/tmp
    environment:
      - DOMAIN=${domain}
      - DASHBOARD_URL=https://dashboard.${domain}
      - GIRDER_MONGO_URI=mongodb://mongo:27017/girder
      - GIRDER_HOST=0.0.0.0
      - GIRDER_WORKER_BROKER=redis://redis/
      - GIRDER_WORKER_BACKEND=redis://redis/
      - GIRDER_NOTIFICATION_REDIS_URL=redis://redis:6379/
      - GOSU_USER=1000:1000:${docker_group}
      - GOSU_CHOWN=/srv/data
      - GIRDER_LOCAL_FONTELLO_ARCHIVE=/girder/clients/web/static/built/fontello.zip
      - HOSTDIR=/
      - WATCHFILES_FORCE_POLLING=true
      - GIRDER_SIVACOR_TRO_GPG_PASSPHRASE=${GIRDER_SIVACOR_TRO_GPG_PASSPHRASE}
      - GIRDER_SIVACOR_TRO_GPG_FINGERPRINT=${GIRDER_SIVACOR_TRO_GPG_FINGERPRINT}
    extra_hosts:
      - "girder.${domain}:host-gateway" # for the local queue
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.girder.rule=Host(`girder.${domain}`)"
        - "traefik.http.routers.girder.entrypoints=https"
        - "traefik.http.routers.girder.tls=true"
        - "traefik.http.services.girder.loadbalancer.server.port=8080"
        - "traefik.http.services.girder.loadbalancer.passhostheader=true"
        - "traefik.swarm.network=wt_proxy"

  redis:
    image: redis:7-bullseye
    networks:
      - celery
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"

networks:
  mongo:
    driver: overlay
  celery:
    driver: overlay
    attachable: true
  proxy:
    driver: overlay

volumes:
  mongo-data: {}
  mongo-cfg: {}
