services:
  sivacor:
    networks:
      - traefik-net
    image: node:22
    working_dir: /app
    volumes:
      - /home/xarth/codes/sivacor/aea-sivacor:/app
    user: "1001:1001"
    entrypoint: ["/bin/bash", "-c", "npm run dev"]
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=wt_traefik-net"
        - "traefik.http.routers.sivacor.rule=Host(`sivacor.${domain}`)"
        - "traefik.http.routers.sivacor.entrypoints=websecure"
        - "traefik.http.routers.sivacor.tls=true"
        - "traefik.http.routers.sivacor.service=sivacor"
        - "traefik.http.services.sivacor.loadbalancer.server.port=4200"
        - "traefik.http.services.sivacor.loadbalancer.passhostheader=true"
    extra_hosts:
      - "girder.${domain}:host-gateway" # for the local queue

  traefik:
    image: traefik:v2.4
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
      - ./traefik/certs/fullchain.pem:/cert.pem
      - ./traefik/certs/privkey.pem:/key.pem
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"
      placement:
        constraints:
          - "node.role == manager"
    environment:
      - TRAEFIK_PROVIDERS_DOCKER_DEFAULTRULE="Host(`\{\{ trimPrefix `/` .Name \}\}.${domain}`)"
    command:
      - "--accesslog=true"
      - "--accesslog.format=json"
      - "--accesslog.filepath=/dev/stdout"

  mongo:
    image: mongo:4.4
    networks:
      - mongo
    volumes:
      - mongo-data:/data/db
      - mongo-cfg:/data/configdb
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"

  local_worker:
    image: xarthisius/girder:5-dev
    networks:
      - celery
      - mongo
    volumes:
      - ./volumes:/srv/data
      - /home/xarth/codes/sivacor/girder-sivacor:/girder-plugins/01-girder-sivacor
      - /tmp:/tmp
    environment:
      - DOMAIN=${domain}
      - GIRDER_MONGO_URI=mongodb://mongo:27017/girder
      - GIRDER_HOST=0.0.0.0
      - GIRDER_WORKER_BROKER=redis://redis/
      - GIRDER_WORKER_BACKEND=redis://redis/
      - GIRDER_NOTIFICATION_REDIS_URL=redis://redis:6379/
      - GIRDER_LOCAL_FONTELLO_ARCHIVE=/girder/clients/web/static/built/fontello.zip
      - GOSU_USER=1001:1001:${docker_group}
      - HOSTDIR=/
    extra_hosts:
      - "girder.${domain}:host-gateway" # for the local queue
    working_dir: /girder-plugins   # for reload
    entrypoint: ["/sbin/tini", "--", "/docker-entrypoint-worker.sh"]
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"

  girder:
    image: xarthisius/girder:5-dev
    networks:
      - traefik-net
      - celery
      - mongo
    volumes:
      - ./volumes/base:/srv/data/base
      - /home/xarth/codes/sivacor/girder-sivacor:/girder-plugins/01-girder-sivacor
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    environment:
      - DOMAIN=${domain}
      - DASHBOARD_URL=https://dashboard.${domain}
      - GIRDER_MONGO_URI=mongodb://mongo:27017/girder
      - GIRDER_HOST=0.0.0.0
      - GIRDER_WORKER_BROKER=redis://redis/
      - GIRDER_WORKER_BACKEND=redis://redis/
      - GIRDER_NOTIFICATION_REDIS_URL=redis://redis:6379/
      - GOSU_USER=1001:1001:${docker_group}
      - GOSU_CHOWN=/srv/data
      - GIRDER_LOCAL_FONTELLO_ARCHIVE=/girder/clients/web/static/built/fontello.zip
      - HOSTDIR=/
      - WATCHFILES_FORCE_POLLING=true
    working_dir: /girder-plugins   # for reload
    extra_hosts:
      - "girder.${domain}:host-gateway" # for the local queue
        # entrypoint: ["/bin/sleep", "infinity"]
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.girder.rule=Host(`girder.${domain}`)"
        - "traefik.http.routers.girder.entrypoints=websecure"
        - "traefik.http.routers.girder.tls=true"
        - "traefik.http.routers.girder.tls.certresolver=default"
        - "traefik.http.routers.girder.tls.domains[0].main=${domain}"
        - "traefik.http.routers.girder.tls.domains[0].sans=*.${domain}"
        - "traefik.http.services.girder.loadbalancer.server.port=8080"
        - "traefik.http.services.girder.loadbalancer.passhostheader=true"
        - "traefik.docker.network=wt_traefik-net"
        - "traefik.http.middlewares.girder.forwardauth.address=http://girder:8080/api/v1/user/authorize/"
        - "traefik.http.middlewares.girder.forwardauth.trustforwardheader=true"

  redis:
    image: redis:7-bullseye
    networks:
      - celery
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=false"

networks:
  traefik-net:
    driver: overlay
  mongo:
    driver: overlay
  celery:
    driver: overlay
    attachable: true

volumes:
  mongo-data: {}
  mongo-cfg: {}
