http:
  routers:
    mainpage_router:
      rule: "Host(`sivacor.org`)"
      entrypoints:
        - http
        - https
      service: main_service
      middlewares:
        - main_middleware
      tls:
        certResolver: cloudflare
    feedback_router:
      rule: "Host(`feedback.sivacor.org`)"
      entrypoints:
        - http
        - https
      service: feedback_service
      middlewares:
        - feedback_middleware
      tls:
        certResolver: cloudflare

  services:
    main_service:
      loadBalancer:
        passHostHeader: true
    feedback_service:
      loadBalancer:
        passHostHeader: true

  middlewares:
    feedback_middleware:
      redirectRegex:
        regex: "^(.*)"
        replacement: "https://cornell.ca1.qualtrics.com/jfe/form/SV_bEnajmkM2qKBr0O"
        permanent: false
    main_middleware:
      redirectRegex:
        regex: "^(.*)"
        replacement: "https://docs.sivacor.org/"
        permanent: false
